### ISSUE TITLE
ProtocolException: 2: Wrong number of arguments on sending CONTROLLER~ADD

### ISSUE THREAD

**Issue by metraport** [wburgers/Open-Zwave-Socket-Server#6]
Hello Willem,

there is an Issue on adding nodes to controller via CONTROLLER~ADD.
I get a ProtocolException: 2: Wrong number of arguments.

I have tested it with  serveral commits of OZW from the last month.

Do you know this issue ?

Best regards,

Mike

**Comment by wburgers** [comment]
Hi Mike,

I'm terribly sorry, I forgot to update the Commandlist!
Since Open-Zwave supports secure devices and secure inclusion, you should specify if you want to use the secure inclusion or the normal inclusion.

To use the secure inclusion, use the command CONTROLLER~ADD~1
To use the normal inclusion, use the command CONTROLLER~ADD~0

I want to expose true or false instead of 1 or 0 respectively, but I have to change my cast for that, so that does not work yet.
Furthermore I could include a default of normal inclusion for CONTROLLER~ADD in the next version, to make things easier.
Please let me know what you think.

In the meantime, I will update the Commandlist to make sure the docs are up to date.

Thank you very much for reporting this!

Best regards,
Willem

**Comment by metraport** [comment]
I think it is ok to set it to ADD~1 or ADD~0.

Thank you for your rapid answer.

Best regards,

Mike
