### ISSUE TITLE
Feature Request (Roomlist NodeID inclusion)

### ISSUE THREAD

**Issue by hellracer** [wburgers/Open-Zwave-Socket-Server#8]
Hi Willem,

Would it be possible if you can add the NodeId of the device that has been assigned in the Location as part of the server response?
e.g

SETNODE~2~Location=Living Room 

[

    {
       "NodeId": 2,
        "Name": "Living Room",
        "CurrentSetPoint": ​0,
        "CurrentTemperature": "0"
    }

]

I hope I made myself clear on this, by the way your inclusion of libsocket is working perfectly :)

**Comment by wburgers** [comment]
Hi :-),

I'm not happy with the response from SETNODE myself, so suggestions are really appreciated!
Let's check if I get this correctly...
Do you want to see the same output as ALIST, but with just the node you set?
Or do you want to include the ROOMLIST output (for the specific room) together with the node ID for this specific option (Location=...) of SETNODE?
In the latter case, all options for SETNODE would give a different output.
Since multiple options can be set in a single SETNODE command, this would be a little more difficult.

I personally think that having a single type of response from all SETNODE commands would be better.
Let me know what you think is best.

**Comment by hellracer** [comment]
Your statement #2 is suffice roomlist output together with its nodeid set by the setnode command. Thanks

**Comment by hellracer** [comment]
Sorry I accidentally close the issue :(

**Comment by wburgers** [comment]
Ok, I'll try to implement that.
I don't have much time this weekend, but the holidays are almost upon us, so this should work in the test branch before the end of the year!
Thanks for your input!
I'm also glad to hear that the socket library is working well 😃.

**Comment by wburgers** [comment]
I've updated the response from a SETNODE command.
It now shows which options have succeeded an which options failed for some reason.
It should be easy to parse this response and know which parts to update.

The response does not include a roomlist extract, because that would be harder to implement in a generic way.
I think this is more elegant.
